/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.sql.*;
import dal.ModuloConexao;
import java.util.Vector;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class TelaBusca extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public TelaBusca() {
        initComponents();
         conexao = ModuloConexao.conector();
          alimentarBox_categoria();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBusca = new javax.swing.JTable();
        cbxBusca1 = new javax.swing.JComboBox<>();
        jButtonAno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbxBusca2 = new javax.swing.JComboBox<>();
        jButtonMes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbxBusca3 = new javax.swing.JComboBox<>();
        jButtonCategoria = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCF - Realizar Busca");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar por Ano:");

        jTableBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Descrição", "Valor", "Categoria", "Usuário", "Status", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBusca.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableBusca);

        cbxBusca1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "2019", "2020", "2021", "2022" }));

        jButtonAno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search_icon.png"))); // NOI18N
        jButtonAno.setContentAreaFilled(false);
        jButtonAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Busca por Mês:");

        cbxBusca2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jButtonMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search_icon.png"))); // NOI18N
        jButtonMes.setContentAreaFilled(false);
        jButtonMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Busca por Categoria:");

        cbxBusca3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jButtonCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search_icon.png"))); // NOI18N
        jButtonCategoria.setContentAreaFilled(false);
        jButtonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo1-removebg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxBusca1, 0, 181, Short.MAX_VALUE)
                            .addComponent(cbxBusca2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxBusca3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAno, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButtonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(cbxBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonAno))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxBusca2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMes)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxBusca3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(586, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnoActionPerformed
        pesquisar_ano();
    }//GEN-LAST:event_jButtonAnoActionPerformed

    private void jButtonMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesActionPerformed
        pesquisar_mes();
    }//GEN-LAST:event_jButtonMesActionPerformed

    private void jButtonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaActionPerformed
       pesquisar_categoria();
    }//GEN-LAST:event_jButtonCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBusca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxBusca1;
    private javax.swing.JComboBox<String> cbxBusca2;
    private javax.swing.JComboBox<String> cbxBusca3;
    private javax.swing.JButton jButtonAno;
    private javax.swing.JButton jButtonCategoria;
    private javax.swing.JButton jButtonMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBusca;
    // End of variables declaration//GEN-END:variables

    private void pesquisar_ano(){

      String sql = "SELECT lancamentoID as ID,tipolancamento as Tipo, descricao as Descrição, valor as Valor, cod_categoria as Categoria, cod_usuario as Usuário, status_lancamento as Status, data_lancamento as Data FROM lancamentofinanceiro WHERE YEAR (data_lancamento)=?";
       
      try {
          
        pst = conexao.prepareStatement(sql);
        pst.setString(1,cbxBusca1.getSelectedItem().toString());
        rs = pst.executeQuery();
        
        jTableBusca.setModel(DbUtils.resultSetToTableModel(rs));
          
        } catch (SQLException e) {
              JOptionPane.showMessageDialog(null, "Erro ComboBox Ano" + e);
        }

    }
    
     private void pesquisar_mes(){

      String sql = "SELECT lancamentoID as ID,tipolancamento as Tipo, descricao as Descrição, valor as Valor, cod_categoria as Categoria, cod_usuario as Usuário, status_lancamento as Status, data_lancamento as Data FROM lancamentofinanceiro WHERE MONTH (data_lancamento)=?";
       
      try {
          
        pst = conexao.prepareStatement(sql);
        pst.setString(1,cbxBusca2.getSelectedItem().toString());
        rs = pst.executeQuery();
        
        jTableBusca.setModel(DbUtils.resultSetToTableModel(rs));
          
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, "Erro ComboBox Mês" + e);
        }

    }
      Vector<Integer> id_categoria = new Vector();
     private void alimentarBox_categoria(){
         
          String sql = ("SELECT * FROM categoria_lancamentofinanceiro ORDER BY descricao_categoria");
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                id_categoria.addElement(rs.getInt(1));
                cbxBusca3.addItem(rs.getString(2));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao Alimentar ComboBox Categoria" + e);
        }
     }
     
     private void pesquisar_categoria(){
         
         // Recebe o indice da categoria selecionada na combobox
        int codcat = cbxBusca3.getSelectedIndex();
        codcat = codcat - 1;
        
         String sql = "SELECT lancamentoID as ID,tipolancamento as Tipo, descricao as Descrição, valor as Valor, cod_categoria as Categoria, cod_usuario as Usuário, status_lancamento as Status, data_lancamento as Data FROM lancamentofinanceiro WHERE cod_categoria=?";
       
      try {
          
        pst = conexao.prepareStatement(sql);
        pst.setInt(1,id_categoria.get(codcat));
        rs = pst.executeQuery();
        
        jTableBusca.setModel(DbUtils.resultSetToTableModel(rs));
          
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, "Erro ComboBox Categoria" + e);
        }

         
         
         
     }
    
    
}
