/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static java.lang.Thread.sleep;

public class TelaSplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form TelaSplashScreen
     */
    public TelaSplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelTexto = new javax.swing.JLabel();
        jLabelLoading = new javax.swing.JLabel();
        jLabelContador = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo1-removebg.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 120, 80));

        jLabelTexto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTexto.setForeground(new java.awt.Color(0, 51, 102));
        jLabelTexto.setText("CONTROLE FINANCEIRO");
        getContentPane().add(jLabelTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 230, 30));

        jLabelLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Dual Ring-1s-81px.gif"))); // NOI18N
        getContentPane().add(jLabelLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 80, 70));

        jLabelContador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContador.setText("0%");
        getContentPane().add(jLabelContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 50, 20));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/splashBackgroundEditada.png"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 340));

        setSize(new java.awt.Dimension(540, 343));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Tela de Splash
        
        new Thread(){
            int i=0;
            
            public void run(){
                while(i<100){
                    i=i+10;
                    
                    // mostra número na label contador
                    jLabelContador.setText(String.valueOf(i)+ "%");
                    
                    try {
                        sleep(600);
                    } catch (InterruptedException e) {
                    }
                }
                // fecha a splash
                TelaSplashScreen.this.dispose();
                //Chama a tela principal
               new TelaLogin().setVisible(true);
            }
        }.start();
        
        
        
       
        
         
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelContador;
    private javax.swing.JLabel jLabelLoading;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTexto;
    // End of variables declaration//GEN-END:variables
}
